### ISSUE TITLE
Possibility of saving tasks selecting the directory

### ISSUE THREAD

**Issue by ghost** [svijee/taskwarrior-androidapp#59]
It's useful if we could select the media (microSD) and the directory in which we want to save files.

**Comment by svijee** [comment]
Hi,

sorry for my late reply.

In the near future I will move the task datafiles back to the internal storage. I don't see a good reason to save the datafiles on the external storage, because every app, with the permission to read/write the external storage, can modify them. Also the datafiles aren't actually big.

Anyway I will include a export-feature, to export the task datafiles to the external storage.

If you have any better suggestions, let me know, thanks! :)
